#!/usr/bin/env bash
#
# bootstrap-hugo-github-pages.sh
# --------------------------------
# Usage:   ./bootstrap-hugo-github-pages.sh [site-name] [github-user]
# Example: ./bootstrap-hugo-github-pages.sh docs awesome-dev
#
# Creates a Hugo project with:
#   • Ananke theme (as a git submodule)
#   • TND SEO module  (meta tags + JSON-LD)
#   • Sample Markdown post with SEO front-matter
#   • GitHub Actions workflow to deploy to gh-pages
#
# Prerequisites:
#   • Hugo ≥ 0.125   • Git   • A GitHub repo already created
#   • Optional: GH CLI or GITHUB_TOKEN to push automatically
set -euo pipefail

SITE_NAME="${1:-hugo-site}"
GITHUB_USER="${2:-CHANGE_ME}"          # <-- your GitHub username
REPO_URL="https://github.com/${GITHUB_USER}/${SITE_NAME}.git"
BASE_URL="https://${GITHUB_USER}.github.io/${SITE_NAME}/"

echo "🏗  Creating Hugo site: $SITE_NAME"
hugo new site "$SITE_NAME" --force
cd "$SITE_NAME"

echo "🔧 Initialising Git repository"
git init -q
git remote add origin "$REPO_URL"

echo "🎨 Adding Ananke theme as submodule"
git submodule add \
  https://github.com/theNewDynamic/gohugo-theme-ananke.git \
  themes/ananke

echo "🔌 Adding the TND SEO module (new path)"
hugo mod init "${GITHUB_USER}/${SITE_NAME}"
hugo mod get github.com/theNewDynamic/hugo-module-tnd-seo@latest

echo "📝 Writing config.toml"
cat > config.toml <<EOF
baseURL      = "${BASE_URL}"
languageCode = "en-us"
title        = "My Hugo Site"
theme        = "ananke"

# Pretty URLs
disablePathToLower = true
uglyURLs           = false

# Sitemap (auto-generated by Hugo)
[sitemap]
  changefreq = "monthly"
  priority   = 0.5
  filename   = "sitemap.xml"

# Hugo Modules
[module]
  proxy = "direct"

  [[module.imports]]
    path = "github.com/theNewDynamic/hugo-module-tnd-seo"
EOF

echo "🗂  Creating sample post"
hugo new --kind post posts/hello-world.md >/dev/null
cat >> content/posts/hello-world.md <<'EOF'
description: "A short teaser shown in search results and social shares."
keywords: ["hugo","static-site","demo"]
EOF

echo "⚙️  Creating GitHub Actions workflow"
mkdir -p .github/workflows
cat > .github/workflows/gh-pages.yml <<'YML'
name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write   # let the action push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
YML

echo "📄 Adding .gitignore"
cat > .gitignore <<'EOF'
# Hugo / Go
/public/
/resources/
/hugo_stats.json
# Node (if you later add JS tooling)
/node_modules/
EOF

echo "✅ Committing initial project"
git add .
git commit -m "Initial Hugo site with Ananke theme and TND SEO module" -q

cat <<EOM

✨ All set!
Next steps:
  1️⃣  git branch -M main
  2️⃣  git push -u origin main          # first push
  3️⃣  In repo Settings ▸ Pages, choose the gh-pages branch.
Every push to main will now rebuild and publish your Hugo site 🚀
EOM
